import {InputsConfig} from '../../../types/inputsconfig';

const inputsConfig: InputsConfig[] = [
  {
    title: 'Name',
    isNumeric: false,
    maxLength: 200,
    placeHolder: 'Name',
    width: 470,
    height: 35,
    multiLine: false,
    dtoKey: 'name',
  },
  {
    title: 'Description',
    isNumeric: false,
    maxLength: 200,
    placeHolder: 'Description',
    width: 470,
    height: 150,
    multiLine: true,
    dtoKey: 'description',
  },
  {
    title: 'Quantity',
    isNumeric: true,
    maxLength: 16,
    placeHolder: '0',
    width: 150,
    height: 35,
    multiLine: false,
    dtoKey: 'quantity',
  },
  {
    title: 'Purchase Price',
    isNumeric: true,
    maxLength: 16,
    placeHolder: '0',
    width: 150,
    height: 35,
    multiLine: false,
    dtoKey: 'purchasePrice',
  },
  {
    title: 'Price Per Unit',
    isNumeric: true,
    maxLength: 16,
    placeHolder: '0',
    width: 150,
    height: 35,
    multiLine: false,
    dtoKey: 'pricePerUnit',
  },

  {
    title: 'Unit',
    width: 150,
    height: 35,
    selectable: true,
    dtoKey: 'unitId',
    selectableDataKey: 'unit',
  },
  {
    title: 'Barcode',
    width: 150,
    height: 35,
    selectable: true,
    dtoKey: 'barcodeId',
    selectableDataKey: 'barcode',
  },
  {
    title: 'Color',
    width: 150,
    height: 35,
    selectable: true,
    dtoKey: 'colorId',
    selectableDataKey: 'color',
  },
  {
    title: 'Label',
    width: 150,
    height: 35,
    selectable: true,
    dtoKey: 'labelId',
    selectableDataKey: 'label',
  },

  {
    title: 'Category',
    width: 150,
    height: 35,
    selectable: true,
    dtoKey: 'categoryId',
    selectableDataKey: 'category',
  },
  {
    title: 'Store',
    width: 150,
    height: 35,
    selectable: true,
    dtoKey: 'storeId',
    selectableDataKey: 'store',
  },
  {
    title: 'Location',
    width: 150,
    height: 35,
    selectable: true,
    requiredDataName: 'store',
    requiredDataDtoKey: 'storeId',
    requiredText: 'Please select Store First',
    selectableDataKey: 'location',
    dtoKey: 'locationId',
  },
  {
    title: 'Supplier',
    width: 150,
    height: 35,
    selectable: true,
    selectableDataKey: 'supplier',
    dtoKey: 'supplierId',
  },
];

export {inputsConfig};
