const inputsConfig = [
  {
    title: 'Name',
    isNumeric: false,
    maxLength: 200,
    placeHolder: 'Name',
    width: 160,
    height: 35,
    multiLine: false,
  },
  {
    title: 'Description',
    isNumeric: false,
    maxLength: 200,
    placeHolder: 'Description',
    width: 200,
    height: 35,
    multiLine: true,
  },
  {
    title: 'Unit',
    width: 130,
    height: 35,
    selectable: true,
  },
  {
    title: 'Barcode',
    width: 130,
    height: 35,
    selectable: true,
  },
  {
    title: 'Category',
    width: 130,
    height: 35,
    selectable: true,
  },
  {
    title: 'Store',
    width: 130,
    height: 35,
    selectable: true,
  },
  {
    title: 'Location',
    width: 130,
    height: 35,
    selectable: true,
  },
  {
    title: 'Supplier',
    width: 130,
    height: 35,
    selectable: true,
  },
  {
    title: 'Quantity',
    isNumeric: true,
    maxLength: 16,
    placeHolder: '0',
    width: 100,
    height: 35,
    multiLine: false,
  },
  {
    title: 'Purchase Price',
    isNumeric: true,
    maxLength: 16,
    placeHolder: '0',
    width: 100,
    height: 35,
    multiLine: false,
  },
  {
    title: 'Price Per Unit',
    isNumeric: true,
    maxLength: 16,
    placeHolder: '0',
    width: 100,
    height: 35,
    multiLine: false,
  },
];

export {inputsConfig};
