export enum RouteNames {
  LOGIN = 'Login',
  DRAWER = 'Drawer',
  WAREHOUSE = 'Warehouse',
  CLIENTS = 'Clients',
  PROJECTS = 'Projects',
  ORDERS = 'Orders',
  PURCHASES = 'Purchases',
  PRODUCT_INFO = 'Info',
  HOME = 'Home',
  CONFIG = 'Config',
  TRACKVIEW = 'TrackView',
  SCAN = 'Scan',
  DASHBOARD = 'Dashboard',
  PRODUCTS = 'Products',
}
