import {InputsConfig} from '../../types/inputsconfig';

const inputsConfig: InputsConfig[] = [
  {
    title: 'Name',
    isNumeric: false,
    maxLength: 60,
    placeHolder: 'Name',
    width: 470,
    height: 35,
    multiLine: false,
    dtoKey: 'name',
  },
  {
    title: 'Category',
    width: 230,
    height: 35,
    selectable: true,
    dtoKey: 'categoryId',
    selectableDataKey: 'category',
    isDisableForEdit: true,
  },
  {
    title: 'Code',
    width: 230,
    height: 35,
    dtoKey: 'code',
    isNumeric: true,
    maxLength: 6,
    isCode: true,
    requiredDataDtoKey: 'categoryId',
    requiredDataName: 'category',
    requiredText: 'Set Category First',
    isDisableForEdit: true,
  },
  {
    title: 'Description',
    isNumeric: false,
    maxLength: 120,
    placeHolder: 'Description',
    width: 470,
    height: 150,
    multiLine: true,
    dtoKey: 'description',
  },

  {
    title: 'Quantity',
    isNumeric: true,
    maxLength: 16,
    placeHolder: '0',
    width: 150,
    height: 30,
    multiLine: false,
    dtoKey: 'quantity',
  },
  {
    title: 'Unit',
    width: 150,
    height: 30,
    selectable: true,
    dtoKey: 'unitId',
    selectableDataKey: 'unit',
    isDisableForEdit: true,
  },
  {
    title: 'Cost Price',
    isNumeric: true,
    maxLength: 16,
    placeHolder: '0',
    width: 150,
    height: 30,
    multiLine: false,
    dtoKey: 'costPrice',
  },
  {
    title: 'Product Attributes',
    customComponentKeyName: 'productAttributes',
  },
  {
    title: 'Sell Price',
    isNumeric: true,
    maxLength: 16,
    placeHolder: '0',
    width: 150,
    height: 30,
    multiLine: false,
    dtoKey: 'sellPrice',
  },
  {
    title: 'Color',
    width: 150,
    height: 35,
    selectable: true,
    dtoKey: 'colorId',
    selectableDataKey: 'color',
  },
  {
    title: 'Label',
    width: 150,
    height: 35,
    selectable: true,
    dtoKey: 'labelId',
    selectableDataKey: 'label',
  },
  {
    title: 'Store',
    width: 150,
    height: 35,
    selectable: true,
    dtoKey: 'storeId',
    selectableDataKey: 'store',
  },
  {
    title: 'Location',
    width: 150,
    height: 35,
    selectable: true,
    requiredDataName: 'store',
    requiredDataDtoKey: 'storeId',
    requiredText: 'Please select Store First',
    selectableDataKey: 'location',
    dtoKey: 'locationId',
  },
  {
    title: 'Supplier',
    width: 150,
    height: 35,
    selectable: true,
    selectableDataKey: 'supplier',
    dtoKey: 'supplierId',
  },
];

export {inputsConfig};
