const FONT = {
  FONT_SIZE_VERY_SMALL: 9,
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 14,
  FONT_SIZE_LARGE: 16,
  FONT_SIZE_MEGA: 18,
  FONT_BOLD: '700' as '700',
  FONT_FAMILY: 'Calibri',
};

export default FONT;
