export const ApiTags = [
  'items',
  'itemInputs',
  'itemOptions',
  'clients',
  'qrCode',
  'item',
  'projects',
  'clientForPicker',
  'orders',
  'codeSuggestions',
  'itemForOrder',
  'projectsForPicker',
  'purchases',
  'itemForPurchase',
] as const;
