export const ApiTags = [
  'items',
  'itemInputs',
  'itemOptions',
  'clients',
  'qrCode',
  'item',
  'projects',
  'clientForPicker',
  'orders',
  'codeSuggestions',
  'itemForOrder',
  'projectsForPicker',
  'purchases',
  'itemForPurchase',
  'projectOrders',
  'otherExpenses',
  'inventoryTrackData',
  'projectTypes',
  'user',
  'activeProjects'
] as const;
